/**
 * Configuration for GLTF Props to load in 3D scenes
 */
export interface PropConfig {
  id: string;
  modelPath: string;
  position: [number, number, number];
  rotation?: [number, number, number];
  scale?: number | [number, number, number];
  enableCollisions?: boolean;
  castShadows?: boolean;
  receiveShadows?: boolean;
}

/**
 * Configuration for Procedural Props (generated without external files)
 */
export interface ProceduralPropConfig {
  id: string;
  type: 'pallet' | 'barrel' | 'traffic-cone' | 'safety-barrier' | 'office-printer' | 'office-phone' | 'filing-cabinet' | 'office-plant' | 'office-door' | 'office-window' | 'office-painting' | 'office-poster' | 'desk-lamp' | 'ceiling-lamp' | 'office-sofa' | 'coffee-table' | 'wall-clock' | 'wall-calendar' | 'vending-machine' | 'water-cooler' | 'emergency-exit-sign' | 'fire-extinguisher' | 'reception-desk' | 'visitor-chair' | 'bookshelf' | 'whiteboard' | 'cafeteria-table' | 'cafeteria-chair' | 'decorative-carpet';
  position: [number, number, number];
  rotation?: [number, number, number];
  scale?: number;
  enableCollisions?: boolean;
  castShadows?: boolean;
  receiveShadows?: boolean;
  colorVariant?: number; // 0-2 for color variations
}

/**
 * SCENARIO_PROPS Configuration
 * 
 * RECOMMENDED FREE SOURCES FOR INDUSTRIAL GLTF MODELS:
 * 
 * 1. KENNEY.NL (CC0 License - Public Domain)
 *    - City Kit (Industrial): https://kenney.nl/assets/city-kit-industrial
 *    - Conveyor Kit: https://kenney.nl/assets/conveyor-kit
 *    - Download includes: GLB, FBX, OBJ formats
 * 
 * 2. POLY PIZZA (Various CC licenses)
 *    - Traffic Cone: https://poly.pizza/m/lAx8JytxGD (Quaternius, CC0)
 *    - Pallet with Boxes: https://poly.pizza/m/9TQMjCMu26x (Colin McKibben, CC-BY)
 *    - Truck: https://poly.pizza/m/cPVFA5uTr9l (jeremy, CC-BY)
 * 
 * 3. QUATERNIUS.COM (CC0 License)
 *    - Free industrial props: https://quaternius.com/
 * 
 * HOW TO ADD MODELS:
 * 1. Download GLB/GLTF file from source above
 * 2. Place in /public/models/props/ directory
 * 3. Add configuration below with correct path
 * 4. Test in game and adjust position/scale/rotation as needed
 */

/**
 * PROCEDURAL PROPS - Generated directly in Babylon.js
 * No external files needed, full control over size and performance
 */
export const SCENARIO_PROCEDURAL_PROPS: Record<string, ProceduralPropConfig[]> = {
  warehouse: [
    // Pallets
    {
      id: 'pallet_01',
      type: 'pallet',
      position: [8, 0, -10],
      rotation: [0, Math.PI / 6, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'pallet_02',
      type: 'pallet',
      position: [10, 0, -10],
      rotation: [0, -Math.PI / 4, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'pallet_03',
      type: 'pallet',
      position: [-12, 0, 8],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Barrels
    {
      id: 'barrel_01',
      type: 'barrel',
      position: [-8, 0, -12],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_02',
      type: 'barrel',
      position: [-9.5, 0, -12],
      rotation: [0, Math.PI / 3, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_03',
      type: 'barrel',
      position: [12, 0, 10],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Traffic cones
    {
      id: 'cone_01',
      type: 'traffic-cone',
      position: [-4, 0, 6],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    {
      id: 'cone_02',
      type: 'traffic-cone',
      position: [-2, 0, 6],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    {
      id: 'cone_03',
      type: 'traffic-cone',
      position: [0, 0, 6],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    
    // Safety barriers
    {
      id: 'barrier_01',
      type: 'safety-barrier',
      position: [-14, 0, 0],
      rotation: [0, Math.PI / 2, 0],
      scale: 0.8,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
  ],
  
  factory: [
    // Barrels (Industrial area)
    {
      id: 'barrel_01',
      type: 'barrel',
      position: [-10, 0, -8],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_02',
      type: 'barrel',
      position: [-11.5, 0, -8],
      rotation: [0, Math.PI / 4, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_03',
      type: 'barrel',
      position: [8, 0, -8],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_04',
      type: 'barrel',
      position: [10, 0, -6],
      rotation: [0, Math.PI / 6, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_05',
      type: 'barrel',
      position: [-6, 0, 10],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Safety barriers (Construction zones)
    {
      id: 'barrier_01',
      type: 'safety-barrier',
      position: [8, 0, -12],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrier_02',
      type: 'safety-barrier',
      position: [-12, 0, 6],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrier_03',
      type: 'safety-barrier',
      position: [0, 0, -10],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrier_04',
      type: 'safety-barrier',
      position: [12, 0, 4],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Traffic cones (Hazard marking)
    {
      id: 'cone_01',
      type: 'traffic-cone',
      position: [5, 0, 8],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    {
      id: 'cone_02',
      type: 'traffic-cone',
      position: [7, 0, 8],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    {
      id: 'cone_03',
      type: 'traffic-cone',
      position: [-4, 0, -4],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    {
      id: 'cone_04',
      type: 'traffic-cone',
      position: [-6, 0, -4],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    {
      id: 'cone_05',
      type: 'traffic-cone',
      position: [3, 0, -6],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
    },
    
    // Pallets (Material storage)
    {
      id: 'pallet_01',
      type: 'pallet',
      position: [10, 0, 10],
      rotation: [0, Math.PI / 3, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'pallet_02',
      type: 'pallet',
      position: [-8, 0, 8],
      rotation: [0, -Math.PI / 4, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'pallet_03',
      type: 'pallet',
      position: [6, 0, -10],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'pallet_04',
      type: 'pallet',
      position: [-10, 0, -12],
      rotation: [0, Math.PI / 6, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
  ],
  
  laboratory: [
    // Barrels (chemical storage)
    {
      id: 'barrel_01',
      type: 'barrel',
      position: [-8, 0, -6],
      scale: 0.8,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'barrel_02',
      type: 'barrel',
      position: [-9.2, 0, -6],
      scale: 0.8,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Safety barriers
    {
      id: 'barrier_01',
      type: 'safety-barrier',
      position: [0, 0, -8],
      scale: 0.7,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
  ],
  
  office: [
    // Filing cabinets
    {
      id: 'filing_cabinet_01',
      type: 'filing-cabinet',
      position: [-10, 0, 6],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'filing_cabinet_02',
      type: 'filing-cabinet',
      position: [-10, 0, 3],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'filing_cabinet_03',
      type: 'filing-cabinet',
      position: [10, 0, -8],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'filing_cabinet_04',
      type: 'filing-cabinet',
      position: [10, 0, -5],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'filing_cabinet_05',
      type: 'filing-cabinet',
      position: [-12, 0, -10],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Office printers
    {
      id: 'printer_01',
      type: 'office-printer',
      position: [-8, 0.75, -4],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'printer_02',
      type: 'office-printer',
      position: [6, 0.75, 8],
      rotation: [0, Math.PI / 3, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'printer_03',
      type: 'office-printer',
      position: [8, 0.75, -10],
      rotation: [0, -Math.PI / 4, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Office phones
    {
      id: 'phone_01',
      type: 'office-phone',
      position: [-6, 0.75, 2],
      rotation: [0, Math.PI / 6, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'phone_02',
      type: 'office-phone',
      position: [4, 0.75, -2],
      rotation: [0, -Math.PI / 4, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'phone_03',
      type: 'office-phone',
      position: [-2, 0.75, -8],
      rotation: [0, Math.PI / 3, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'phone_04',
      type: 'office-phone',
      position: [10, 0.75, 4],
      rotation: [0, -Math.PI / 6, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'phone_05',
      type: 'office-phone',
      position: [-10, 0.75, -2],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'phone_06',
      type: 'office-phone',
      position: [2, 0.75, 10],
      rotation: [0, -Math.PI / 3, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Decorative plants
    {
      id: 'plant_01',
      type: 'office-plant',
      position: [-12, 0, 10],
      scale: 1.2,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_02',
      type: 'office-plant',
      position: [12, 0, 10],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_03',
      type: 'office-plant',
      position: [-12, 0, -12],
      scale: 0.9,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_04',
      type: 'office-plant',
      position: [12, 0, -12],
      scale: 1.1,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_05',
      type: 'office-plant',
      position: [-6, 0, -12],
      scale: 0.8,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_06',
      type: 'office-plant',
      position: [6, 0, 12],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_07',
      type: 'office-plant',
      position: [0, 0.75, 6],
      scale: 0.7,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'plant_08',
      type: 'office-plant',
      position: [0, 0.75, -6],
      scale: 0.7,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Doors
    {
      id: 'door_01',
      type: 'office-door',
      position: [0, 0, -14.9],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'door_02',
      type: 'office-door',
      position: [-14.9, 0, 0],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'door_03',
      type: 'office-door',
      position: [14.9, 0, 0],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Windows
    {
      id: 'window_01',
      type: 'office-window',
      position: [0, 1.5, 14.95],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'window_02',
      type: 'office-window',
      position: [6, 1.5, 14.95],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'window_03',
      type: 'office-window',
      position: [-6, 1.5, 14.95],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'window_04',
      type: 'office-window',
      position: [14.95, 1.5, 6],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    
    // Paintings
    {
      id: 'painting_01',
      type: 'office-painting',
      position: [-14.95, 1.8, 8],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'painting_02',
      type: 'office-painting',
      position: [-14.95, 1.8, -4],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'painting_03',
      type: 'office-painting',
      position: [14.95, 1.8, -10],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'painting_04',
      type: 'office-painting',
      position: [14.95, 1.8, 8],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'painting_05',
      type: 'office-painting',
      position: [4, 1.8, -14.95],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    
    // Safety posters
    {
      id: 'poster_01',
      type: 'office-poster',
      position: [-14.92, 1.5, -8],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'poster_02',
      type: 'office-poster',
      position: [14.92, 1.5, 2],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'poster_03',
      type: 'office-poster',
      position: [14.92, 1.5, -4],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'poster_04',
      type: 'office-poster',
      position: [-6, 1.5, -14.92],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'poster_05',
      type: 'office-poster',
      position: [-10, 1.5, -14.92],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'poster_06',
      type: 'office-poster',
      position: [8, 1.5, -14.92],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    
    // Desk lamps (on workstations)
    {
      id: 'desk_lamp_01',
      type: 'desk-lamp',
      position: [-6, 0.75, 2],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'desk_lamp_02',
      type: 'desk-lamp',
      position: [4, 0.75, -2],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'desk_lamp_03',
      type: 'desk-lamp',
      position: [-2, 0.75, -8],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'desk_lamp_04',
      type: 'desk-lamp',
      position: [10, 0.75, 4],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'desk_lamp_05',
      type: 'desk-lamp',
      position: [-10, 0.75, -2],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    {
      id: 'desk_lamp_06',
      type: 'desk-lamp',
      position: [2, 0.75, 10],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: false,
    },
    
    // Ceiling lamps
    {
      id: 'ceiling_lamp_01',
      type: 'ceiling-lamp',
      position: [-6, 2.9, -4],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'ceiling_lamp_02',
      type: 'ceiling-lamp',
      position: [6, 2.9, -4],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'ceiling_lamp_03',
      type: 'ceiling-lamp',
      position: [-6, 2.9, 4],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'ceiling_lamp_04',
      type: 'ceiling-lamp',
      position: [6, 2.9, 4],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'ceiling_lamp_05',
      type: 'ceiling-lamp',
      position: [0, 2.9, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    
    // Relax area - Sofas (with color variations)
    {
      id: 'sofa_01',
      type: 'office-sofa',
      position: [-8, 0, 10],
      rotation: [0, 0, 0],
      scale: 1.0,
      colorVariant: 0, // Gray-blue
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'sofa_02',
      type: 'office-sofa',
      position: [-8, 0, 8],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      colorVariant: 1, // Warm brown
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'sofa_03',
      type: 'office-sofa',
      position: [8, 0, 10],
      rotation: [0, 0, 0],
      scale: 1.0,
      colorVariant: 2, // Dark green
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Coffee tables (in relax area)
    {
      id: 'coffee_table_01',
      type: 'coffee-table',
      position: [-8, 0, 9],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'coffee_table_02',
      type: 'coffee-table',
      position: [8, 0, 8.5],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'coffee_table_03',
      type: 'coffee-table',
      position: [0, 0, -12],
      rotation: [0, Math.PI / 4, 0],
      scale: 0.9,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Wall clocks
    {
      id: 'wall_clock_01',
      type: 'wall-clock',
      position: [0, 2.2, 14.95],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'wall_clock_02',
      type: 'wall-clock',
      position: [-14.95, 2.2, 0],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    
    // Wall calendars
    {
      id: 'wall_calendar_01',
      type: 'wall-calendar',
      position: [14.92, 1.5, 6],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'wall_calendar_02',
      type: 'wall-calendar',
      position: [-14.92, 1.5, 4],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'wall_calendar_03',
      type: 'wall-calendar',
      position: [12, 1.5, -14.92],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    
    // Vending machines (break area)
    {
      id: 'vending_machine_01',
      type: 'vending-machine',
      position: [-10, 0, 12],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'vending_machine_02',
      type: 'vending-machine',
      position: [-11.5, 0, 12],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Water coolers (break area)
    {
      id: 'water_cooler_01',
      type: 'water-cooler',
      position: [-6, 0, 12],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'water_cooler_02',
      type: 'water-cooler',
      position: [10, 0, 12],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Emergency exit signs (illuminated)
    {
      id: 'exit_sign_01',
      type: 'emergency-exit-sign',
      position: [0, 2.3, -14.92],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'exit_sign_02',
      type: 'emergency-exit-sign',
      position: [-14.92, 2.3, 0],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    {
      id: 'exit_sign_03',
      type: 'emergency-exit-sign',
      position: [14.92, 2.3, 0],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: false,
      receiveShadows: false,
    },
    
    // Fire extinguishers
    {
      id: 'extinguisher_01',
      type: 'fire-extinguisher',
      position: [-14.8, 0, -6],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'extinguisher_02',
      type: 'fire-extinguisher',
      position: [14.8, 0, -6],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'extinguisher_03',
      type: 'fire-extinguisher',
      position: [-14.8, 0, 6],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'extinguisher_04',
      type: 'fire-extinguisher',
      position: [2, 0, 14.8],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Reception area
    {
      id: 'reception_desk',
      type: 'reception-desk',
      position: [0, 0, -12],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'visitor_chair_01',
      type: 'visitor-chair',
      position: [-1.5, 0, -10.5],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'visitor_chair_02',
      type: 'visitor-chair',
      position: [-0.5, 0, -10.5],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'visitor_chair_03',
      type: 'visitor-chair',
      position: [0.5, 0, -10.5],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'visitor_chair_04',
      type: 'visitor-chair',
      position: [1.5, 0, -10.5],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Bookshelves (side walls)
    {
      id: 'bookshelf_01',
      type: 'bookshelf',
      position: [-14.8, 0, -10],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'bookshelf_02',
      type: 'bookshelf',
      position: [-14.8, 0, -2],
      rotation: [0, Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'bookshelf_03',
      type: 'bookshelf',
      position: [14.8, 0, 2],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'bookshelf_04',
      type: 'bookshelf',
      position: [14.8, 0, -2],
      rotation: [0, -Math.PI / 2, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'bookshelf_05',
      type: 'bookshelf',
      position: [-4, 0, 14.8],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Whiteboards/Presentation screens (meeting areas)
    {
      id: 'whiteboard_01',
      type: 'whiteboard',
      position: [-8, 0.75, -14.9],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'whiteboard_02',
      type: 'whiteboard',
      position: [6, 0.75, 14.9],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'whiteboard_03',
      type: 'whiteboard',
      position: [14.9, 0.75, -8],
      rotation: [0, -Math.PI / 2, 0],
      scale: 0.8,
      enableCollisions: false,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Cafeteria area tables
    {
      id: 'cafeteria_table_01',
      type: 'cafeteria-table',
      position: [-3, 0, 10],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_table_02',
      type: 'cafeteria-table',
      position: [-3, 0, 13],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_table_03',
      type: 'cafeteria-table',
      position: [2, 0, 10],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_table_04',
      type: 'cafeteria-table',
      position: [2, 0, 13],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Cafeteria chairs (4 per table = 16 total)
    {
      id: 'cafeteria_chair_01',
      type: 'cafeteria-chair',
      position: [-3.7, 0, 9.4],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_02',
      type: 'cafeteria-chair',
      position: [-2.3, 0, 9.4],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_03',
      type: 'cafeteria-chair',
      position: [-3.7, 0, 10.6],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_04',
      type: 'cafeteria-chair',
      position: [-2.3, 0, 10.6],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_05',
      type: 'cafeteria-chair',
      position: [-3.7, 0, 12.4],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_06',
      type: 'cafeteria-chair',
      position: [-2.3, 0, 12.4],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_07',
      type: 'cafeteria-chair',
      position: [-3.7, 0, 13.6],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_08',
      type: 'cafeteria-chair',
      position: [-2.3, 0, 13.6],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_09',
      type: 'cafeteria-chair',
      position: [1.3, 0, 9.4],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_10',
      type: 'cafeteria-chair',
      position: [2.7, 0, 9.4],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_11',
      type: 'cafeteria-chair',
      position: [1.3, 0, 10.6],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_12',
      type: 'cafeteria-chair',
      position: [2.7, 0, 10.6],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_13',
      type: 'cafeteria-chair',
      position: [1.3, 0, 12.4],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_14',
      type: 'cafeteria-chair',
      position: [2.7, 0, 12.4],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_15',
      type: 'cafeteria-chair',
      position: [1.3, 0, 13.6],
      rotation: [0, 0, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    {
      id: 'cafeteria_chair_16',
      type: 'cafeteria-chair',
      position: [2.7, 0, 13.6],
      rotation: [0, Math.PI, 0],
      scale: 1.0,
      enableCollisions: true,
      castShadows: true,
      receiveShadows: true,
    },
    
    // Decorative carpets (different areas with color variants)
    {
      id: 'carpet_relax_01',
      type: 'decorative-carpet',
      position: [-8, 0.001, 9],
      rotation: [0, 0, 0],
      scale: 1.0,
      colorVariant: 0, // Warm red-brown for relaxation area
      enableCollisions: false,
      castShadows: false,
      receiveShadows: true,
    },
    {
      id: 'carpet_relax_02',
      type: 'decorative-carpet',
      position: [8, 0.001, 9],
      rotation: [0, 0, 0],
      scale: 1.0,
      colorVariant: 0, // Warm red-brown for relaxation area
      enableCollisions: false,
      castShadows: false,
      receiveShadows: true,
    },
    {
      id: 'carpet_reception',
      type: 'decorative-carpet',
      position: [0, 0.001, -11],
      rotation: [0, 0, 0],
      scale: 1.2,
      colorVariant: 1, // Cool blue-gray for reception
      enableCollisions: false,
      castShadows: false,
      receiveShadows: true,
    },
    {
      id: 'carpet_cafeteria',
      type: 'decorative-carpet',
      position: [-0.5, 0.001, 11.5],
      rotation: [0, 0, 0],
      scale: 1.4,
      colorVariant: 2, // Olive green for cafeteria
      enableCollisions: false,
      castShadows: false,
      receiveShadows: true,
    },
  ],
};

export const SCENARIO_PROPS: Record<string, PropConfig[]> = {
  warehouse: [
    // === KENNEY.NL - CITY KIT (INDUSTRIAL) ===
    // Download: https://kenney.nl/assets/city-kit-industrial
    // Uncomment when you have the models:
    
    // {
    //   id: 'warehouse_forklift_01',
    //   modelPath: '/models/props/kenney-forklift.glb',
    //   position: [-12, 0, -8],
    //   rotation: [0, Math.PI / 6, 0],
    //   scale: 2.0,
    //   enableCollisions: true,
    //   castShadows: true,
    //   receiveShadows: true,
    // },
    // {
    //   id: 'warehouse_pallet_stack_01',
    //   modelPath: '/models/props/kenney-pallet-stack.glb',
    //   position: [10, 0, -12],
    //   rotation: [0, 0, 0],
    //   scale: 1.8,
    //   enableCollisions: true,
    //   castShadows: true,
    //   receiveShadows: true,
    // },
    // {
    //   id: 'warehouse_barrel_01',
    //   modelPath: '/models/props/kenney-barrel.glb',
    //   position: [8, 0, 10],
    //   scale: 1.5,
    //   enableCollisions: true,
    //   castShadows: true,
    // },
    // {
    //   id: 'warehouse_barrel_02',
    //   modelPath: '/models/props/kenney-barrel.glb',
    //   position: [10, 0, 10],
    //   rotation: [0, Math.PI / 3, 0],
    //   scale: 1.5,
    //   enableCollisions: true,
    //   castShadows: true,
    // },
    
    // === POLY PIZZA - TRAFFIC CONES ===
    // Download: https://poly.pizza/m/lAx8JytxGD (Quaternius)
    
    // {
    //   id: 'warehouse_cone_01',
    //   modelPath: '/models/props/poly-traffic-cone.glb',
    //   position: [-5, 0, 8],
    //   scale: 1.2,
    //   enableCollisions: true,
    //   castShadows: true,
    // },
    // {
    //   id: 'warehouse_cone_02',
    //   modelPath: '/models/props/poly-traffic-cone.glb',
    //   position: [-3, 0, 8],
    //   scale: 1.2,
    //   enableCollisions: true,
    //   castShadows: true,
    // },
  ],
  
  factory: [
    // === KENNEY.NL - CONVEYOR KIT ===
    // Download: https://kenney.nl/assets/conveyor-kit
    
    // {
    //   id: 'factory_conveyor_01',
    //   modelPath: '/models/props/kenney-conveyor-straight.glb',
    //   position: [-15, 0, 0],
    //   rotation: [0, Math.PI / 2, 0],
    //   scale: 2.0,
    //   enableCollisions: false, // Allow walking over
    //   castShadows: true,
    //   receiveShadows: true,
    // },
    // {
    //   id: 'factory_machine_large_01',
    //   modelPath: '/models/props/kenney-industrial-machine.glb',
    //   position: [-8, 0, -10],
    //   scale: 2.5,
    //   enableCollisions: true,
    //   castShadows: true,
    //   receiveShadows: true,
    // },
    
    // === POLY PIZZA - TRUCK ===
    // Download: https://poly.pizza/m/cPVFA5uTr9l (jeremy)
    
    // {
    //   id: 'factory_truck_01',
    //   modelPath: '/models/props/poly-truck.glb',
    //   position: [12, 0, -15],
    //   rotation: [0, Math.PI, 0],
    //   scale: 3.0,
    //   enableCollisions: true,
    //   castShadows: true,
    //   receiveShadows: true,
    // },
  ],
  
  laboratory: [
    // Laboratory can use smaller industrial props:
    // - Safety cabinets
    // - Lab equipment
    // - Safety signs
  ],
  
  office: [
    // Office can use:
    // - Desk props
    // - Computer equipment
    // - Office plants
    // - Filing cabinets
  ],
};
